#!/usr/bin/env sh

package="$1"
dir=""
if [ "x$2" != "x" ] ; then
	dir="$2/"
fi

# version=$(npm show ${package} version)
version="8.2.0"
archive="${package}-${version}.tgz"
curl --silent --remote-name \
  "https://registry.npmjs.org/${package}/-/${archive}"
mkdir "${package}"
tar xzf "${archive}" --strip-components 1 -C "${dir}${package}"
rm "${archive}"